#language: android
#jdk: oraclejdk8
#before_install:
#- yes | sdkmanager "platforms;android-28"
#
#env:
#  global:
#    - ANDROID_API_LEVEL=28
#    - ANDROID_BUILD_TOOLS_VERSION=29.0.2
##    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
#    - TRAVIS_SECURE_ENV_VARS=true
#
#android:
#  components:
#    # The BuildTools version used by your project
#    - tools
#    - platform-tools
#    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
#    - extra-android-m2repository
#    - extra-google-android-support
#
#    # The SDK version used to compile your project
#    - android-$ANDROID_API_LEVEL
#  licenses:
#    - '.+'
#
#script:
#    - ./gradlew clean
##    - ./gradlew install
##    - ./gradlew bintrayUpload
#    - ./gradlew assembleDebug


language: android
android:
  components:
    # The BuildTools version used by your project
    - build-tools-29.0.2
    # The SDK version used to compile your project
    - android-29
    # Android support Repository
    - extra-android-m2repository
    # Support Library
#    - extra-android-m2repository-com-android-support
script:
  # 生成APK
#  - ./gradlew clean
  #    - ./gradlew install
  #    - ./gradlew bintrayUpload
#  - ./gradlew assembleDebug
  -  chmod +x gradlew
  - ./gradlew assembleRelease

before_deploy:     # 部署之前
  # 使用 mv 命令进行修改 apk 文件的名字
  - mv app/release/app-release.apk app/release/buffArms.apk

#部署
deploy:
  #部署到github release
  #此外Travis CI还支持发布到fir.im、AWS、Google app Engine
  provider: releases
  #Github oauth token
  api_key: "$GIT_TOKEN2"
  #部署文件路径：对于Android就部署生成的apk文件
  file:
    - app/release/buffArms.apk
  #避免Travis在部署清空生成的apk文件
  skip_cleanup: true
  #发布时机
  on:
    #tags设置为true表示只有在tag的情况下才部署
    tags: true
    branch:  master
#  tag: latest
#    #指定只有当tag的为vx.x.x（如v1.0.0）才发包
#    condition: '$TRAVIS_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+$'
#before_install:
#  - chmod a+x gradlew
#  - rvm install 2.1.5
#  - gem install rubyzip -v 1.3.0
#  - gem install fir-cli
#after_deploy:
#  - fir p app/release/buffArms.apk -T $FIR_IM -c "`git cat-file tag $TRAVIS_TAG`"
#after_deploy:
#  - fir publish app/release/buffArms.apk -T $FIR_IM -c "`git cat-file tag $TRAVIS_TAG`"

before_install:
  - chmod +x gradlew
  - gem install fir-cli #安装fir命令行客户端
  deploy:
    provider: releases
#    api_key:
#      secure: O2o06fEDsYyVp********************Kj/rPwK8O1XZnrhIbSnLOIekqKTwMA1zK/UqMliMWGCmG1vTLsDwL1GxA3ZRhTopCNYPXF4kE8iQ1TtTTMJHlPNRm4PObPu+6Tqcaj7ajkHuYqkQhVGmZyPfXgC5H4J71GQkf57YnAmDSvUXit7fsaIkb0Gxfx8nOma2EHdSHXe7g8RTD55UGg65rezuyrEKsvh8JzVqycC/cVtu6L4+s21bwR7U+UxBAOXVko0nnUiJCKnRAXu9U41i2vcfPC5/MHYcg/b2HfwYAkqx+fqVnW888FumwWru/jE3aps4b+I4Ci02b63yYgLKc0ShB5WtukfFivSZLRg1a8GW6kpgv5+5+Ntn1KcCWv4MLio/4qsRLi544Of643QFnr8arKMLZrRiAZWBh2xexAVlgyzYdfqdQEwZm5hqpfaU3vUZWx8kqvZ+hZ2/utnsPi0iD5cknz1ewHUMBl7ctz6lqgEp9K/0TFOR+YshpBTWa4HkAO2QSGcVUB83W4TM3B5pOKA/IOX6GZflnbNvsYOYYbvI0e5i3X25enKR7NPaFNljRdOOWEKLfM6CHqMdkAroUlJ57BNTHqRUX7K4ZHE8jfdY93e7LgRWGPhDsihtfuMRKr9T7uh2mCK88bkLncMgRwmhxtOfQUI=
    file: app/release/buffArms.apk
    skip_cleanup: true
#    on:
#      repo: JianxunRao/MoqiDump
  after_deploy:
    - fir login $FIR_IM #fir账号的Token
    - fir me #打印身份信息,验证是否登录成功
    - fir p app/release/buffArms.apk #自动发布应用至fir内测平台
notifications:
  email:
    - weijiangxing777@qq.com
